In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime
from datetime import timedelta
import glob
import geopandas as gpd
import geobr

In [2]:
plt.style.use("seaborn-v0_8-whitegrid")
plt.rcParams['axes.grid'] = False
plt.rcParams['font.size'] = '14'
plt.rcParams["font.family"] = "Times New Roman"

In [6]:
# variables
threshold_pr_max = 450 #[mm]
threshold_pr_min = 0 #[mm]
file_path = './1 - Organized data gauge/BRAZIL/BRAZIL_DAILY_1961_2024.h5'
cleaned_path = './1 - Organized data gauge/BRAZIL/DATASETS/BRAZIL_DAILY_1961_2024_CLEANED.h5'

# Data processing

In [7]:
df_data = pd.read_hdf(file_path, key = 'table_data', encoding = 'utf-8')
df_data

         gauge_code   datetime  rain_mm
0        110018901A 2021-01-01     6.30
1        110018901A 2021-01-02     1.79
2        110018901A 2021-01-03     0.00
3        110018901A 2021-01-04    16.15
4        110018901A 2021-01-05     1.58
...             ...        ...      ...
2908882    88690050 2023-12-27     0.00
2908883    88690050 2023-12-28     0.00
2908884    88690050 2023-12-29     2.00
2908885    88690050 2023-12-30     0.00
2908886    88690050 2023-12-31     0.00

[123617525 rows x 3 columns]

In [8]:
df_info = pd.read_hdf(file_path, key = 'table_info', encoding = 'utf-8')
df_info = df_info[df_info['gauge_code'].isin(df_data['gauge_code'].unique())]
df_info

,gauge_code,state,city,name_station,lat,long,responsible,source,state_abbreviation
0,00047000,PARÁ,SALINÓPOLIS,SALINÓPOLIS,-0.650000,-47.550000,INMET,HIDROWEB,PA
1,00047002,PARÁ,SALINÓPOLIS,SALINÓPOLIS,-0.623100,-47.353600,ANA,HIDROWEB,PA
2,00047003,PARÁ,CURUÇA,CURUÇA,-0.737500,-47.853600,ANA,HIDROWEB,PA
3,00047004,PARÁ,PRIMAVERA,PRIMAVERA,-0.929400,-47.099400,ANA,HIDROWEB,PA
4,00047005,PARÁ,MARAPANIM,MARUDA,-0.633600,-47.658300,ANA,HIDROWEB,PA
...,...,...,...,...,...,...,...,...,...
18977,S713,MATO GROSSO DO SUL,NOVA ANDRADINA,NOVA ANDRADINA | S713,-22.078611,-53.465833,INMET,INMET,MS
18978,S714,MATO GROSSO DO SUL,PEDRO GOMES,PEDRO GOMES | S714,-18.072778,-54.548889,INMET,INMET,MS
18979,S715,MATO GROSSO DO SUL,RIBAS DO RIO PARDO,RIBAS DO RIO PARDO | S715,-20.466694,-53.763028,INMET,INMET,MS
18980,S716,MATO GROSSO DO SUL,SANTA RITA DO PARDO,SANTA RITA DO PARDO | S716,-21.305889,-52.820375,INMET,INMET,MS
18981,S717,MATO GROSSO DO SUL,SELVIRIA,SELVIRIA | S717,-20.351389,-51.430278,INMET,INMET,MS

In [9]:
gauge_counts = df_info['gauge_code'].value_counts() # Count occurrences of each gauge_code
print(gauge_counts)

gauge_code
00047000      1
251600301C    1
251700101C    1
251650802U    1
251620102A    1
             ..
02040006      1
02040007      1
02040008      1
02040009      1
S717          1
Name: count, Length: 18370, dtype: int64

In [10]:
# df_complete_info = pd.merge(df_data, df_info, on='gauge_code', how = 'inner').sort_values('lat', ascending = True)
# # .dropna(how='any')
# df_complete_info

In [11]:
df_data_filtered = df_data[(df_data['rain_mm'] >= threshold_pr_min) & (df_data['rain_mm'] <= threshold_pr_max)]
df_data_filtered = df_data_filtered[df_data_filtered['gauge_code'].isin(df_info['gauge_code'].unique().tolist())]
df_data_filtered['gauge_code'].unique().tolist()

['110018901A',
 '110020501A',
 '110020502A',
 '120010401A',
 '120032801A',
 '120040101A',
 '120040101H',
 '120040102A',
 '120070801A',
 '130002901A',
 '130006001A',
 '130008601A',
 '130010201A',
 '130014401A',
 '130020101A',
 '130030002A',
 '130050801A',
 '130060701A',
 '130063101A',
 '130063102A',
 '130068001A',
 '130080501A',
 '130090401A',
 '130110002A',
 '130115901A',
 '130150601A',
 '130160501A',
 '130165401A',
 '130170401A',
 '130170402A',
 '130185201A',
 '130185202A',
 '130190203A',
 '130190205A',
 '130200901A',
 '130220701A',
 '130240501A',
 '130240502A',
 '130250405A',
 '130250406A',
 '130260301H',
 '130260302H',
 '130260303H',
 '130260310A',
 '130260326A',
 '130260327A',
 '130260328A',
 '130260329A',
 '130260330A',
 '130260331A',
 '130260332A',
 '130260333A',
 '130260334A',
 '130260335A',
 '130260336A',
 '130260337A',
 '130290001A',
 '130310601A',
 '130330401A',
 '130340301A',
 '130340302A',
 '130340303A',
 '130353601A',
 '130353602A',
 '130356901A',
 '130356902A',
 '130370001A',
 '130380901A',
 '130380902A',
 '130390801A',
 '130400503A',
 '130406201A',
 '130406202A',
 '130410401A',
 '130420301A',
 '130423701A',
 '130430201A',
 '130440101A',
 '140010001A',
 '140010002A',
 '140010003A',
 '140010004A',
 '140010005A',
 '140070401A',
 '150010701A',
 '150010702A',
 '150010703A',
 '150040401A',
 '150040402A',
 '150050302A',
 '150060202A',
 '150060203A',
 '150085901A',
 '150100601A',
 '150120401A',
 '150140201A',
 '150140201H',
 '150140203A',
 '150140204A',
 '150140205A',
 '150140206A',
 '150140207A',
 '150140208A',
 '150140209A',
 '150140210A',
 '150170901A',
 '150215201A',
 '150295401A',
 '150350701A',
 '150350702A',
 '150360601A',
 '150360602A',
 '150380401A',
 '150390301A',
 '150420801A',
 '150420802A',
 '150420803A',
 '150420805A',
 '150420806A',
 '150480202A',
 '150480203A',
 '150497601A',
 '150503101A',
 '150510602A',
 '150530402A',
 '150540301A',
 '150553601A',
 '150553602A',
 '150553603A',
 '150553604A',
 '150553605A',
 '150600501A',
 '150616101A',
 '150619501A',
 '150619502A',
 '150670801A',
 '150670802A',
 '150680701A',
 '150680702A',
 '150680703A',
 '150680704A',
 '150745801A',
 '150750801A',
 '150780501A',
 '150797901A',
 '150805001A',
 '150810001A',
 '150835701A',
 '160030302A',
 '160030303A',
 '160030304A',
 '160030305A',
 '160060002A',
 '160060003A',
 '170210901A',
 '170210902A',
 '170210903A',
 '170210904A',
 '170215801A',
 '170220801A',
 '170730601A',
 '170740501A',
 '170820501A',
 '170900501A',
 '171660401A',
 '171820401A',
 '171830301A',
 '171886501A',
 '172020001A',
 '172030901A',
 '172210701A',
 '210020401A',
 '210043601A',
 '210047701A',
 '210050102A',
 '210083201A',
 '210090701A',
 '210095601A',
 '210100401A',
 '210120201A',
 '210120202A',
 '210130101A',
 '210140001A',
 '210177201A',
 '210180601A',
 '210210102A',
 '210220001A',
 '210232501A',
 '210250701A',
 '210270501A',
 '210300001A',
 '210300002A',
 '210300003A',
 '210315801A',
 '210320801A',
 '210320802A',
 '210330701A',
 '210330702A',
 '210340601A',
 '210340602A',
 '210350501A',
 '210355401A',
 '210360401A',
 '210390101A',
 '210400801A',
 '210410701A',
 '210420601A',
 '210480001A',
 '210510401A',
 '210515301A',
 '210530201A',
 '210530202A',
 '210530203A',
 '210530204A',
 '210540101A',
 '210545001A',
 '210570801A',
 '210580701A',
 '210590601A',
 '210594801A',
 '210596302A',
 '210630001A',
 '210635902A',
 '210660701A',
 '210663101A',
 '210670601A',
 '210675501A',
 '210680501A',
 '210690401A',
 '210720901A',
 '210745601A',
 '210760501A',
 '210780301A',
 '210820701A',
 '210830601A',
 '210845401A',
 '210850401A',
 '210870201A',
 '210880101A',
 '210890001A',
 '210910601A',
 '210930401A',
 '210945201A',
 '210960101A',
 '210975901A',
 '210980901A',
 '211000501A',
 '211010401A',
 '211027802A',
 '211080701A',
 '211130002A',
 '211130003A',
 '211130004A',
 '211130005A',
 '211130006A',
 '211130007A',
 '211130008A',
 '211130009A',
 '211130010A',
 '211140901A',
 '211150801A',
 '211153202A',
 '211172201A',
 '211210001A',
 '211220901A',
 '211223301A',
 '211227401A',
 '211245601A',
 '211270401A',
 '211280301A',
 '211290201A',
 '220005301U',
 '220025101C',
 '220030101A',
 '220105101C',
 '220110101C',
 '220120001A',
 '220150701A',
 '220155601C',
 '220173901C',
 '220190301U',
 '220194501A',
 '220200001A',
 '220202601C',
 '220208301A',
 '220220801A',
 '220230701C',
 '220260401A',
 '220260401C',
 '220265301A',
 '220270301A',
 '220277801C',
 '220320601C',
 '220335401C',
 '220345301U',
 '220350301U',
 '220370101A',
 '220385901C',
 '220390901A',
 '220390902A',
 '220430301C',
 '220465901A',
 '220470901C',
 '220515101C',
 '220520101U',
 '220553201C',
 '220556501C',
 '220580501A',
 '220605001C',
 '220610001A',
 '220620901A',
 '220670401C',
 '220700901C',
 '220720701C',
 '220750402A',
 '220770201A',
 '220770202A',
 '220770203A',
 '220777701C',
 '220780101C',
 '220790001U',
 '220800701C',
 '220810601C',
 '220820501U',
 '220830401A',
 '220830401C',
 '220850202A',
 '220910401C',
 '220915301A',
 '220937701C',
 '220965801C',
 '221000301C',
 '221005201A',
 '221020101C',
 '221030001C',
 '221035901C',
 '221080501U',
 '221100101A',
 '221100102A',
 '221100103A',
 '221100104A',
 '221110001A',
 '221120901A',
 '221130801C',
 '221170401C',
 '230020001A',
 '230030901U',
 '230050701C',
 '230070501C',
 '230075401A',
 '230075401H',
 '230075402A',
 '230075403A',
 '230090301U',
 '230110901C',
 '230120801C',
 '230160401C',
 '230170301A',
 '230170301U',
 '230190101C',
 '230200801C',
 '230210701A',
 '230210701C',
 '230230501A',
 '230240401A',
 '230250301C',
 '230270101C',
 '230280001A',
 '230280001C',
 '230280002A',
 '230300601A',
 '230300601U',
 '230320401C',
 '230360001C',
 '230370901A',
 '230370902A',
 '230370903A',
 '230370903H',
 '230370904A',
 '230370905A',
 '230370906A',
 '230380801U',
 '230390701A',
 '230400401A',
 '230400401C',
 '230410301A',
 '230410301C',
 '230410302A',
 '230420201A',
 '230420202A',
 '230420204H',
 '230430101C',
 '230435001A',
 '230435001C',
 '230440001A',
 '230440004A',
 '230440005A',
 '230440005H',
 '230440006A',
 '230440007A',
 '230440008A',
 '230440009A',
 '230440010A',
 '230440011A',
 '230440014A',
 '230440015A',
 '230440016A',
 '230460801C',
 '230470701A',
 '230470702A',
 '230490506H',
 '230510001C',
 '230535701C',
 '230540701A',
 '230540701C',
 '230540702A',
 '230550601A',
 '230550602A',
 '230560501C',
 '230590201U',
 '230600901C',
 '230610801A',
 '230610801C',
 '230620701A',
 '230630601C',
 '230640501C',
 '230650401U',
 '230670201C',
 '230680101C',
 '230690001C',
 '230700701A',
 '230700701C',
 '230700702A',
 '230700703A',
 '230700704A',
 '230700705A',
 '230700706A',
 '230710601U',
 '230720501C',
 '230730401A',
 '230730401C',
 '230740301C',
 '230750201A',
 '230750201C',
 '230750207H',
 '230760101A',
 '230763501A',
 '230763501U',
 '230765001A',
 '230765002A',
 '230765003A',
 '230765004A',
 '230770001A',
 '230770002A',
 '230780901A',
 '230800501A',
 '230810401A',
 '230810401C',
 '230820301A',
 '230830201C',
 '230835101C',
 '230840101A',
 '230840101C',
 '230850001C',
 '230870801C',
 '230870802A',
 '230870803A',
 '230870804A',
 '230870805A',
 '230870809H',
 '230880701A',
 '230890601A',
 '230930001C',
 '230940901U',
 '230945801C',
 '230960701C',
 '230980501A',
 '230990401A',
 '231040701C',
 '231050601A',
 '231050601C',
 '231050602A',
 '231070401C',
 '231080301C',
 '231090201C',
 '231130601C',
 '231135501C',
 '231140501A',
 '231140501C',
 '231150401A',
 '231160301C',
 '231170201C',
 '231180101A',
 '231180101U',
 '231180102A',
 '231190001U',
 '231195901U',
 '231200701A',
 '231200701U',
 '231200702H',
 '231210601C',
 '231230401C',
 '231270001A',
 '231270001C',
 '231290801A',
 '231290802A',
 '231290811H',
 '231310401A',
 '231310401C',
 '231325201C',
 '231340101U',
 '231370801C',
 '231375701C',
 '231400301C',
 '231410201A',
 '231410202A',
 '240020801A',
 '240030701C',
 '240070301A',
 '240090101C',
 '240100801A',
 '240130501C',
 '240140401A',
 '240200601A',
 '240200601C',
 '240200602A',
 '240220401A',
 '240220402A',
 '240230301C',
 '240250101A',
 '240260001A',
 '240260002A',
 '240310301U',
 '240360801A',
 '240370701C',
 '240420001A',
 '240450701A',
 '240470501A',
 '240485301A',
 '240560301A',
 '240570201C',
 '240580101A',
 '240580101C',
 '240610601A',
 '240650201C',
 '240720301A',
 '240730201C',
 '240750001A',
 '240780701C',
 '240800302A',
 '240800303A',
 '240800304A',
 '240800305A',
 '240800306A',
 '240800308A',
 '240810201A',
 '240810202A',
 '240810203A',
 '240810204A',
 '240810205A',
 '240810206A',
 '240810207A',
 '240810208A',
 '240830001C',
 '240840901C',
 '240890401C',
 '240930801A',
 '240940701C',
 '240990201A',
 '241025601A',
 '241080101C',
 '241120501C',
 '241220301A',
 '241220302A',
 '241260901C',
 '241280701A',
 '241280701U',
 '241290601C',
 '241390401C',
 '241440701A',
 '241460501A',
 '241470401A',
 '250030401A',
 '250050201A',
 '250157501C',
 '250180701A',
 '250180702A',
 '250180703A',
 '250300101A',
 '250320901A',
 '250320902A',
 '250320903A',
 '250390201C',
 '250400901A',
 '250400901C',
 '250400902A',
 '250400903A',
 '250400904A',
 '250400905A',
 '250400906A',
 '250400907A',
 '250430602U',
 '250440501C',
 '250450401C',
 '250480101A',
 '250600401C',
 '250700202U',
 '250750701A',
 '250750702A',
 '250750703A',
 '250750704A',
 '250750705A',
 '250750706A',
 '250750707A',
 '250770501C',
 '250800001C',
 '250850501C',
 '250910701A',
 '250920601C',
 '250930501A',
 '250970101C',
 '250980001A',
 '251080801A',
 '251080801C',
 '251080802A',
 '251130101C',
 '251140001C',
 '251190501A',
 '251210101C',
 '251250702U',
 '251270501C',
 '251310901C',
 '251350501C',
 '251360401C',
 '251380201C',
 '251390101A',
 '251400801C',
 '251420602U',
 '251490901C',
 '251530201A',
 '251600301C',
 '251610201C',
 '251620101A',
 '251620101C',
 '251620102A',
 '251650802U',
 '251700101C',
 '251710001U',
 '260005401A',
 '260005402A',
 '260010401A',
 '260020301U',
 '260020302A',
 '260030201A',
 '260040101A',
 '260040102A',
 '260050001A',
 '260050002A',
 '260060901A',
 '260060901U',
 '260070801A',
 '260080701A',
 '260080701C',
 '260080702A',
 '260090601A',
 '260100301A',
 '260105201A',
 '260110201A',
 '260110202A',
 '260120101A',
 '260120101C',
 '260130001A',
 '260130002A',
 '260130016H',
 '260140901A',
 '260140901H',
 '260140902A',
 '260140903A',
 '260140917H',
 '260150802A',
 '260170601A',
 '260170601C',
 '260180501A',
 '260190401A',
 '260190401C',
 '260200101A',
 '260210001A',
 '260210001C',
 '260220901A',
 '260230801A',
 '260230802A',
 '260240701C',
 '260250601A',
 '260260501C',
 '260270401A',
 '260280301A',
 '260290201G',
 '260290202A',
 '260290203A',
 '260290204A',
 '260290205A',
 '260300901A',
 '260300902A',
 '260310801A',
 '260310802A',
 '260320701A',
 '260320701C',
 '260330601A',
 '260340501A',
 '260345401A',
 '260345401G',
 '260345402A',
 '260345403A',
 '260345404A',
 '260345405A',
 '260345406A',
 '260350401A',
 '260360301A',
 '260370201A',
 '260380101A',
 '260390001A',
 '260390001C',
 '260392601A',
 '260392601U',
 '260410601A',
 '260410602A',
 '260410603A',
 '260410605A',
 '260410606A',
 '260410607A',
 '260410608A',
 '260415501A',
 '260420502A',
 '260420503A',
 '260420504A',
 '260430401A',
 '260440301A',
 '260450201A',
 '260460101A',
 '260470001A',
 '260480901A',
 '260490801A',
 '260510301A',
 '260510301C',
 '260515201A',
 '260515201C',
 '260515202A',
 '260520201A',
 '260520202A',
 '260530101A',
 '260540001A',
 '260545901A',
 '260550901A',
 '260560801A',
 '260560802A',
 '260570701A',
 '260570701C',
 '260570702A',
 '260580601A',
 '260580601C',
 '260590501A',
 '260590502A',
 '260590518H',
 '260600201A',
 '260600201C',
 '260610101A',
 '260610102A',
 '260620001A',
 '260620002A',
 '260620003A',
 '260620003H',
 '260630901A',
 '260630901C',
 '260650701A',
 '260650701C',
 '260660601A',
 '260660601C',
 '260670501A',
 '260680403A',
 '260680404A',
 '260680405A',
 '260680406A',
 '260690301A',
 '260690301C',
 '260700001A',
 '260710901A',
 '260720801A',
 '260720801G',
 '260720802A',
 '260720804A',
 '260720805A',
 '260730701A',
 '260730702A',
 '260730703A',
 '260740601A',
 '260740601C',
 '260750501A',
 '260750501U',
 '260760401A',
 '260765301A',
 '260765302A',
 '260770301A',
 '260775201A',
 '260780201A',
 '260790101A',
 '260790101G',
 '260790102A',
 '260790102G',
 '260790103A',
 '260790103G',
 '260790104A',
 '260790104G',
 '260790105G',
 '260790106A',
 '260790106G',
 '260790107A',
 '260790108A',
 '260790109A',
 '260790115H',
 '260790119H',
 '260795001A',
 '260795002A',
 '260795004H',
 '260800801A',
 '260800801C',
 '260805701A',
 '260805701C',
 '260810701A',
 '260820602A',
 '260825501A',
 '260830501A',
 '260840401A',
 '260840401C',
 '260845301A',
 '260850301A',
 '260860201A',
 '260870101A',
 '260875001A',
 '260875001U',
 '260875002A',
 '260880001A',
 '260880001C',
 '260890901A',
 '260900601A',
 '260910501A',
 '260915401A',
 '260920401A',
 '260920402A',
 '260930301A',
 '260930301C',
 '260940201A',
 '260940202A',
 '260950101A',
 '260950102A',
 '260950103A',
 '260950104A',
 '260960001A',
 '260960001G',
 '260960002A',
 '260960003A',
 '260960004A',
 '260960005A',
 '260970901A',
 '260970901C',
 '260980801A',
 '260990701A',
 '260990701C',
 '261000402A',
 '261000403A',
 '261010301A',
 '261010301U',
 '261020201A',
 '261030101A',
 '261040001A',
 '261040002A',
 '261050901A',
 '261060801A',
 '261060802A',
 '261070702A',
 '261070703A',
 '261070704A',
 '261070705A',
 '261070707A',
 '261080601A',
 '261080601C',
 '261090501A',
 '261090501C',
 '261100201A',
 '261110101A',
 '261110101C',
 '261110102A',
 '261110102C',
 '261110103A',
 '261110103C',
 '261110104A',
 '261110105A',
 '261110106A',
 '261120001A',
 '261120002A',
 '261130901A',
 '261130902A',
 '261140801A',
 '261140802A',
 '261150701A',
 '261150702A',
 '261150704A',
 '261153301A',
 '261160601A',
 '261160603A',
 '261160603G',
 '261160604A',
 '261160604G',
 '261160605A',
 '261160605G',
 '261160606A',
 '261160606G',
 '261160607A',
 '261160607G',
 '261160608A',
 '261160609A',
 '261160609G',
 '261160610A',
 '261160610G',
 '261160611G',
 '261160612A',
 '261160613A',
 '261160613G',
 '261160614A',
 '261160615A',
 '261160615G',
 '261160616G',
 '261160617A',
 '261160618A',
 '261160619A',
 '261160620A',
 '261160621A',
 '261160622A',
 '261160623A',
 '261170501A',
 '261180401A',
 '261180402A',
 '261190301A',
 '261190302A',
 '261190303A',
 '261200001A',
 '261210901A',
 '261210901C',
 '261220801A',
 '261230701A',
 '261240601A',
 '261240601C',
 '261245501C',
 '261247101A',
 '261250501A',
 '261250501U',
 '261255401A',
 '261255401C',
 '261260401C',
 '261270301A',
 '261280201A',
 '261280201C',
 '261290101A',
 '261290102A',
 '261300801C',
 '261310701A',
 '261320601A',
 '261330501A',
 '261330501U',
 '261330502A',
 '261340401A',
 '261350301A',
 '261350302A',
 '261360201C',
 '261370101A',
 '261370102A',
 '261370103A',
 '261370104A',
 '261370105A',
 '261380001A',
 '261390901A',
 '261390901C',
 '261400601A',
 '261400601U',
 '261410501A',
 '261410501C',
 '261410502C',
 '261420401A',
 '261420402A',
 '261430301A',
 '261440201A',
 '261450101A',
 '261460001A',
 '261460001C',
 '261470901A',
 '261470902A',
 '261480801A',
 '261480801C',
 '261485701A',
 '261485702A',
 '261500301A',
 ...]

In [12]:
print(len(df_data_filtered), len(df_data_filtered['gauge_code'].unique()), len(df_info), len(df_info['gauge_code'].unique()))

123595839 18370 18370 18370

In [13]:
df_info_filtered = df_info[df_info['gauge_code'].isin(df_data_filtered['gauge_code'].unique())]
# df_info_filtered['gauge_code'].unique().tolist()

print(len(df_info) - len(df_info_filtered), 'gauges were removed due to the precipitation threshold.')

0 gauges were removed due to the precipitation threshold.

In [14]:
print(len(df_data)- len(df_data_filtered), 'data points were removed due to the precipitation threshold.')

21686 data points were removed due to the precipitation threshold.

In [15]:
print((len(df_info) - len(df_info_filtered)), 'gauges were removed due to the precipitation threshold.')

0 gauges were removed due to the precipitation threshold.

In [16]:
print((len(df_data) - len(df_data_filtered))/len(df_data)*100,"%")

0.01754282008153779 %

In [17]:
print((len(df_info) - len(df_info_filtered))/len(df_info)*100,"%")

0.0 %

In [18]:
df_data_filtered.to_hdf(cleaned_path, key='table_data', mode='r+', complevel=9, format = 'table', append = False, complib='blosc:lz4', encoding='utf-8')
df_info_filtered.to_hdf(cleaned_path, key='table_info', mode='r+', complevel=9, format = 'table', append = False, complib='blosc:lz4', encoding='utf-8')

c:\ProgramData\anaconda3\Lib\site-packages\tables\leaf.py:409: RuntimeWarning: overflow encountered in scalar multiply
  expected_mb = (expectedrows * rowsize) // MB

In [19]:
with pd.HDFStore(cleaned_path) as store:
        keys = store.keys()
        print(f"Current tables in {cleaned_path}:")
        for key in keys:
            print(f"  - {key.lstrip('/')}")

Current tables in ./1 - Organized data gauge/BRAZIL/DATASETS/BRAZIL_DAILY_1961_2024_CLEANED.h5:
  - table_data
  - table_data_outlier_filtered
  - table_info
  - table_outlier
  - table_outlier_filter_1
  - table_outlier_filter_1_export
  - table_outlier_filter_2_export
  - table_preclassif

In [20]:
df_info_filtered = pd.read_hdf(cleaned_path, key='table_info', encoding='utf-8')
df_info_filtered

,gauge_code,state,city,name_station,lat,long,responsible,source,state_abbreviation
0,00047000,PARÁ,SALINÓPOLIS,SALINÓPOLIS,-0.650000,-47.550000,INMET,HIDROWEB,PA
1,00047002,PARÁ,SALINÓPOLIS,SALINÓPOLIS,-0.623100,-47.353600,ANA,HIDROWEB,PA
2,00047003,PARÁ,CURUÇA,CURUÇA,-0.737500,-47.853600,ANA,HIDROWEB,PA
3,00047004,PARÁ,PRIMAVERA,PRIMAVERA,-0.929400,-47.099400,ANA,HIDROWEB,PA
4,00047005,PARÁ,MARAPANIM,MARUDA,-0.633600,-47.658300,ANA,HIDROWEB,PA
...,...,...,...,...,...,...,...,...,...
18977,S713,MATO GROSSO DO SUL,NOVA ANDRADINA,NOVA ANDRADINA | S713,-22.078611,-53.465833,INMET,INMET,MS
18978,S714,MATO GROSSO DO SUL,PEDRO GOMES,PEDRO GOMES | S714,-18.072778,-54.548889,INMET,INMET,MS
18979,S715,MATO GROSSO DO SUL,RIBAS DO RIO PARDO,RIBAS DO RIO PARDO | S715,-20.466694,-53.763028,INMET,INMET,MS
18980,S716,MATO GROSSO DO SUL,SANTA RITA DO PARDO,SANTA RITA DO PARDO | S716,-21.305889,-52.820375,INMET,INMET,MS
18981,S717,MATO GROSSO DO SUL,SELVIRIA,SELVIRIA | S717,-20.351389,-51.430278,INMET,INMET,MS